# Generated by Django 4.1.7 on 2023-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_attribute_attributevalue_product_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="description",
            field=models.CharField(
                blank=True, max_length=2500, verbose_name="Описание"
            ),
        ),
    ]
