# Generated by Django 4.1.7 on 2023-03-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_attribute_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название свойства"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2500, verbose_name="Описание"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=500, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Свойство товара",
                "verbose_name_plural": "Свойства товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "verbose_name": "Атрибут товара",
                "verbose_name_plural": "Атрибуты товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="attributevalue",
            options={
                "verbose_name": "Значение Атрибута",
                "verbose_name_plural": "Значения Атрибутов",
            },
        ),
        migrations.CreateModel(
            name="ProductPropertyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=250, verbose_name="Значение")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties2",
                        to="products.product",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products2",
                        to="products.productproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение свойства продукта",
                "verbose_name_plural": "Значения свойств продукта",
                "unique_together": {("product", "property")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductPropertyValue",
                to="products.productproperty",
            ),
        ),
    ]
