# Generated by Django 4.1.7 on 2023-03-08 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_attributevalue_attribute_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="attributes",
            new_name="properties",
        ),
    ]
