# Generated by Django 4.1.7 on 2023-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_rename_attributes_product_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpropertyvalue",
            name="value",
            field=models.CharField(blank=True, max_length=250, verbose_name="Значение"),
        ),
    ]
