# Generated by Django 4.1.7 on 2023-03-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_product_category_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpropertyvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties_trough",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productpropertyvalue",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="products.productproperty",
            ),
        ),
    ]
