# Generated by Django 4.1.7 on 2023-03-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_productpropertyvalue_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpropertyvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties_through",
                to="products.product",
            ),
        ),
    ]
