# Generated by Django 4.1.7 on 2023-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_productproperty_categories_alter_product_properties"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="category",
            name="price_coefficient",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=20,
                verbose_name="Цена за единицу",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="weight_coefficient",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=20,
                verbose_name="Цена за единицу",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meter_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                verbose_name="Цена за метр",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meter_weight",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Вес метра"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ton_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                verbose_name="Цена за тонну",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                verbose_name="Цена за единицу",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_weight",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Вес штуки"
            ),
        ),
    ]
