# Generated by Django 4.1.7 on 2023-03-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_category_price_coefficient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="meter_weight",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_weight",
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                verbose_name="Цена за штуку",
            ),
        ),
    ]
