# Generated by Django 4.1.7 on 2023-03-17 21:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_productproperty_units_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productproperty",
            name="slug",
        ),
        migrations.AddField(
            model_name="productproperty",
            name="code",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="name",
                verbose_name="Код свойства",
            ),
        ),
    ]
