# Generated by Django 4.1.7 on 2023-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_remove_productproperty_slug_productproperty_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproperty",
            name="is_display_in_list",
            field=models.BooleanField(
                default=False, verbose_name="Отображать в списке продкутов?"
            ),
        ),
    ]
