# Generated by Django 4.1.7 on 2023-03-19 11:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_productproperty_is_display_in_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название меню"),
                ),
                (
                    "code",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="name",
                        verbose_name="Код меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.AlterModelOptions(
            name="productproperty",
            options={
                "ordering": ("ordering",),
                "verbose_name": "Свойство товара",
                "verbose_name_plural": "Свойства товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="productpropertyvalue",
            options={
                "ordering": ("property__ordering",),
                "verbose_name": "Значение свойства продукта",
                "verbose_name_plural": "Значения свойств продукта",
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Название пункта меню"
                    ),
                ),
                (
                    "url",
                    models.CharField(max_length=250, verbose_name="Ссылка пункта меню"),
                ),
                (
                    "navigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.navigation",
                        verbose_name="Меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
    ]
