# Generated by Django 4.2 on 2023-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_navigation_alter_productproperty_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parse_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="URL"),
        ),
    ]
