# Generated by Django 4.2 on 2023-04-19 16:51

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_category_parse_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=150,
                populate_from="name",
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=150,
                populate_from="name",
                verbose_name="slug",
            ),
        ),
    ]
