# Generated by Django 4.2 on 2023-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_remove_product_category_productcategories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategories",
            name="is_display",
            field=models.BooleanField(
                default=False, verbose_name="Отображать в категории?"
            ),
        ),
    ]
