# Generated by Django 4.2 on 2023-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_productcategories_is_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="parse_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL парсинга"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parse_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL парсинга"
            ),
        ),
    ]
