# Generated by Django 4.2 on 2023-04-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_product_parse_url_alter_category_parse_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpropertyvalue",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values_through",
                to="products.productproperty",
            ),
        ),
        migrations.CreateModel(
            name="PropertyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=250, verbose_name="Значение")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.productproperty",
                        verbose_name="Свойство",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="prop_values",
            field=models.ManyToManyField(
                related_name="products",
                to="products.propertyvalue",
                verbose_name="Значения свойств",
            ),
        ),
    ]
