# Generated by Django 4.2 on 2023-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_remove_product_prop_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
