# Generated by Django 4.2 on 2023-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_product_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_parsing_successful",
            field=models.BooleanField(default=False, verbose_name="Парсинг успешный"),
        ),
        migrations.AddField(
            model_name="category",
            name="last_parsed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последнего парсинга"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="SEO Description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=350, verbose_name="SEO Title"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="SEO Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=350, verbose_name="SEO Title"
            ),
        ),
    ]
