# Generated by Django 4.2 on 2023-05-16 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0029_category_is_parsing_successful_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="parsed_name",
        ),
    ]
