# Generated by Django 4.2 on 2023-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_rename_name_category_parsed_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Название категории"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parsed_name",
            field=models.CharField(
                max_length=500, verbose_name="Название категории из парсинга"
            ),
        ),
    ]
