# Generated by Django 4.2.1 on 2023-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0032_alter_category_name_alter_category_parsed_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="categories/", verbose_name="Изображение"
            ),
        ),
    ]
