# Generated by Django 4.2.2 on 2023-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="always_in_stock",
            field=models.BooleanField(
                default=False,
                help_text="Не зависит от парсинга, имеет высший приоритет",
                verbose_name="Всегда в наличии",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_ton_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Приоритет отображения цены выше, чем у спаршеной",
                max_digits=20,
                verbose_name="Своя цена за тонну",
            ),
        ),
    ]
