# Generated by Django 4.2.2 on 2023-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0035_alter_product_meter_price_alter_product_ton_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="custom_meter_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Приоритет отображения цены выше, чем у спаршеной",
                max_digits=20,
                verbose_name="Своя цена за метр",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Приоритет отображения цены выше, чем у спаршеной",
                max_digits=20,
                verbose_name="Своя цена за штуку",
            ),
        ),
    ]
